name: Deploy LOGISTIK-UNIKOM

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e

            # Fix DNS Resolution Issue on the server
            echo "nameserver 1.1.1.1" | sudo tee /etc/resolv.conf > /dev/null || true

            cd /var/www/html/unikom-perlengkapan-backend-v2

            git fetch origin dev
            git reset --hard origin/dev

            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan optimize:clear